const AccountRole = {
  SUPER_ADMINISTRATOR: 'SUPER_ADMINISTRATOR',
  ADMINISTRATOR: 'ADMINISTRATOR',
  COMUNA_LOCALITATE_JUDET_ADMINISTRATOR: 'COMUNA_LOCALITATE_JUDET_ADMINISTRATOR',
  MODERATOR: 'MODERATOR',
  SIMPLE_USER: 'SIMPLE_USER',
};

module.exports = AccountRole;
