const AccountRole = {
  TOP_ADMINISTRATOR: 'TOP_ADMINISTRATOR',
  ADMINISTRATOR: 'ADMINISTRATOR',
  ADMIN_JUDET_OR_LOCALITATE_OR_COMUNA: 'ADMIN_JUDET_OR_LOCALITATE_OR_COMUNA',
  ADMIN_JUDET_OR_LOCALITATE_OR_COMUNA_DREPT_PENTRU_MODERATOR: 'ADMIN_JUDET_OR_LOCALITATE_OR_COMUNA_DREPT_PENTRU_MODERATOR',
  SIMPLE_USER: 'SIMPLE_USER',
  MODERATOR: 'MODERATOR',
};

module.exports = AccountRole;
